### PR TITLE
Add ZULIP_SITE config param.

### PR DESCRIPTION
**Pull request by TomaszKolek**

### CODE REVIEW

**Comment by TomaszKolek** [comment]
@matthewbarr It'd be good to have ZULIP_SITE configurable because we'd like to turn off "global" zulip api.
https://github.com/zulip/zulip/issues/1821

**Comment by timabbott** [comment]
BTW @matthewbarr I don't know if you still use Zulip since it's been a few years, but if you don't want to keep maintaining this package, maybe we should transfer it to the Zulip GitHub organization so that the Zulip open source community can maintain it?

**Review by matthewbarr — APPROVED** [review]

**Comment by matthewbarr** [comment]
@timabbott  I'm actually pretty happy to transfer it.  I'm not using puppet & zulip much together right now, because I'm now @ Akamai.  So my group uses puppet a bit, and I use Zulip, but I don't manage servers anymore :)

**Comment by timabbott** [comment]
Cool, sounds good!  Can you transfer the project to by owned by me?  You can do this on the settings page for the repo.  I can then transfer it into the zulip organization (only org admins can transfer into organizations).  Thanks!

**Pull request merged**
